### ISSUE TITLE
Create new DirmonEntry from an existing instance.

### ISSUE THREAD

**Issue by reidmorrison** [rocketjob/rocketjob_mission_control#36]
It can be quite complex to set all the custom values when creating a new dirmon entry. Copying from an existing entry will reduce error when most of the fields are the same.

**Comment by Elro1118** [comment]
I'm working on it

**Comment by Elro1118** [comment]
I've found how to add an **Action** column in Enabled Dirmon Entries Page.

**Comment by Elro1118** [comment]
I found out that if I wanted to show the copy button, I had to add the name button in 
<img width="1132" alt="Screen Shot 2020-04-23 at 8 54 44 AM" src="https://user-images.githubusercontent.com/40242986/80101962-1f6f2400-8540-11ea-931a-a948e41bea23.png">
access_policy.rb

**Comment by Elro1118** [comment]
I found out that if I wanted to show the copy button, I had to add the name button in access_policy.rb
<img width="1132" alt="Screen Shot 2020-04-23 at 8 54 44 AM" src="https://user-images.githubusercontent.com/40242986/80103149-c2746d80-8541-11ea-8cd1-b517b9c2f616.png">

**Comment by Elro1118** [comment]
I'm confused about this part and still cannot create my copy_dirmon_entry_path method. I was advised to review Rails basic tutorial, so I'm doing this now.

**Comment by Elro1118** [comment]
I just created the copy page showing the detail of the selected Dirmon Entry.

**Comment by Elro1118** [comment]
I just sent my PR about this new process. https://github.com/rocketjob/rocketjob_mission_control/pull/65

**Comment by reidmorrison** [comment]
Fixed with https://github.com/rocketjob/rocketjob_mission_control/pull/65.

Thank you @Elro1118
