### ISSUE TITLE
Only display the pause/resume button for jobs that are pausable

### ISSUE THREAD

**Issue by reidmorrison** [rocketjob/rocketjob_mission_control#51]
For example: `job.pausable?`

**Comment by johnsinco** [comment]
https://github.com/rocketjob/rocketjob_mission_control/blob/master/app/views/rocket_job_mission_control/jobs/show.html.erb#L34

Would just be...
```
<% if valid_events.include?(:pause) && can?(:pause, @job) && @job.pausable? %>
```
or am I missing something?  Not sure about the CanCan part, I dont see that in the .gemspec?

**Comment by jgaviria** [comment]
Yes, I think that would do the trick.

**Comment by reidmorrison** [comment]
Perfect!

RJMC uses AccessGranted which closely matches the CanCan syntax, just much lighter weight.
